# Generated by Django 6.0.5 on 2026-06-02 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=500)),
                ('data_encerramento', models.DateField()),
                ('regra_encerramento', models.CharField(max_length=255)),
                ('opcao_sucesso', models.CharField(max_length=255)),
                ('opcao_fracasso', models.CharField(max_length=255)),
                ('link_imagem', models.URLField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('liquidez_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total_sucesso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total_fracasso', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorias', models.ManyToManyField(related_name='mercados', to='accounts.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('percentual_sucesso', models.FloatField()),
                ('percentual_fracasso', models.FloatField()),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='accounts.mercado')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Compra'), (2, 'Venda')])),
                ('quantidade', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mercado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mercado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eh_admin', models.BooleanField(default=False)),
                ('mercados', models.ManyToManyField(related_name='participantes', through='accounts.Operacao', to='accounts.mercado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucesso', models.BooleanField()),
                ('mercado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='accounts.mercado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='operacao',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(max_length=500)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mercado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('eh_sucesso', models.BooleanField()),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mercado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mercado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'mercado', 'eh_sucesso'), name='unique_acao_por_usuario_mercado_tipo')],
            },
        ),
    ]
